tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: not_needed
      user: not_needed
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DB') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WH') }}"
      threads: 1

    prod:
      type: snowflake
      account: not_needed
      user: not_needed
      role: CR_DATA_ENGINEER
      database: DEV_ACCESS
      schema: REPORTING
      warehouse: DEV_ADHOC_WH
      threads: 1
