tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: account
      role: engineer
      user: user
      database: "{{ env_var('SNOWFLAKE_DB') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WH') }}"
      threads: 1

    prod:
      type: snowflake
      account: account
      role: engineer
      user: user
      database: "{{ env_var('SNOWFLAKE_DB') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WH') }}"
      threads: 1
