tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: '_'
      user: '_'
      role: DBT_TRANSFORMED_ROLE
      database: DEV_ACCESS
      schema: REPORTING
      warehouse: DEV_ADHOC_WH
      threads: 1

    prod:
      type: snowflake
      account: not_needed
      user: not_needed
      role: DBT_TRANSFORMED_ROLE
      database: DEV_ACCESS
      schema: REPORTING
      warehouse: PROD_ADHOC_WH
      threads: 1
