tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: not_needed
      user: not_needed
      role: DBT_TRANSFORMED_ROLE
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: REPORTING
      warehouse: DEV_ADHOC_WH
      threads: 1

    prod:
      type: snowflake
      account: not_needed
      user: not_needed
      role: DBT_TRANSFORMED_ROLE
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: REPORTING
      warehouse: PROD_ADHOC_WH
      threads: 1
