tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "not needed"
      user: "not needed"
      role: "temp_role"
      database: "temp_db"
      schema: "temp_schema"
      warehouse: "temp_wh"
      threads: 1

    prod:
      type: snowflake
      account: "not needed"
      user: "not needed"
      role: CR_DATA_ENGINEER
      database: DEV_ACCESS
      schema: REPORTING
      warehouse: DEV_ADHOC_WH
      threads: 1
